image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  # check tf version
  - terraform --version
  # init terraform
  - terraform init
  # tf vars
  - export TF_VAR_ci_jwt=$CI_JOB_JWT && echo $TF_VAR_ci_jwt
  - export TF_VAR_ci_role=$CI_PROJECT_ID && echo $TF_VAR_ci_role

stages:
  - pre-flight
  - validate
  - plan
  - apply

pre-flight:
  stage: pre-flight
  script:
    # check the gitlab vars
    - echo $CI_JOB_JWT
    - echo $CI_PROJECT_ID
    # assign terraform var from env var
    - export TF_VAR_ci_jwt=$CI_JOB_JWT && echo $TF_VAR_ci_jwt
    - export TF_VAR_ci_role=$CI_PROJECT_ID && echo $TF_VAR_ci_role
    #- echo "TF_VAR_ci_jwt=$CI_JOB_JWT" >> vault_tf.env
    #- echo "TF_VAR_ci_role=$CI_PROJECT_ID" >> vault_tf.env
    #- cat vault_tf.env
  #artifacts:
  #  reports:
  #    dotenv: vault_tf.env

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - echo $TF_VAR_ci_jwt && echo $TF_VAR_ci_role
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual